graph:
{%- if pillar.get('reclass', {}).storage is defined %}
{%- from "reclass/map.jinja" import storage with context %}
- host: {{ grains.id }}
  service: reclass.storage
  type: software-config
  relations:
  {%- if storage.data_source.engine == 'git' %}
  - host_external: {{ storage.data_source.address.replace(':', '/').replace('git@', 'http://') }}
    service: external-service
    direction: source
    type: tcp-ssh
  {%- endif %}
{%- endif %}

{#-
  vim: syntax=jinja
-#}
