---
driver:
  name: docker
  hostname: reclass.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: reclass
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - reclass
  pillars:
    top.sls:
      base:
        "*":
          - reclass

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: class_mapping
    provisioner:
      pillars-from-files:
        reclass.sls: tests/pillar/class_mapping.sls

  - name: generate_multi
    provisioner:
      pillars-from-files:
        reclass.sls: tests/pillar/generate_multi.sls

  - name: generate_single
    provisioner:
      pillars-from-files:
        reclass.sls: tests/pillar/generate_single.sls

  - name: storage_local
    provisioner:
      pillars-from-files:
        reclass.sls: tests/pillar/storage_local.sls

  - name: storage_nodes_uri
    provisioner:
      pillars-from-files:
        reclass.sls: tests/pillar/storage_nodes_uri.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
